'use client';
import {useState, useEffect, useRef} from 'react';
import {ArrowLeft, ArrowRight, Check, CheckCircle2, Volume2, Sparkles, BookOpen, Headphones, Layers} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import type {Lesson} from '@/lib/curriculum';
import AudioButton from './AudioButton';
import PracticeStudio from './PracticeStudio';
const steps=['Words','Understand','Listen','Read','Speak','Write','Quick check'];
export default function LessonPlayer({lesson,userId,onExit,onComplete,onPractice}:{lesson:Lesson,userId:string,onExit:()=>void,onComplete:(minutes:number)=>Promise<void>,onPractice:(skill:string,score:number|null,minutes:number,attemptId?:string)=>Promise<void>}){
 const [step,setStep]=useState(0),[selected,setSelected]=useState<Record<string,number>>({}),[checked,setChecked]=useState(false),[finished,setFinished]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[speakingDone,setSpeakingDone]=useState(false),[writingDone,setWritingDone]=useState(false),[transcript,setTranscript]=useState(false);
 const started=useRef(0),practiceMinutes=useRef(0),stepStarted=useRef(0),stepAttempts=useRef<Record<string,string>>({});const [hydrated,setHydrated]=useState(false);const storageKey='stigen-lesson-'+encodeURIComponent(userId)+'-'+lesson.id;
 useEffect(()=>{started.current=Date.now();stepStarted.current=Date.now();const timer=window.setTimeout(()=>{try{const raw=sessionStorage.getItem(storageKey);if(raw){const d=JSON.parse(raw);if(Number.isInteger(d.step)&&d.step>=0&&d.step<=6)setStep(d.step);if(d.selected&&typeof d.selected==='object')setSelected(Object.fromEntries(Object.entries(d.selected).filter(([,v])=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<10)) as Record<string,number>);setSpeakingDone(d.speakingDone===true);setWritingDone(d.writingDone===true);}}catch{}setHydrated(true);},0);return()=>window.clearTimeout(timer);},[storageKey]);
 useEffect(()=>{if(!hydrated)return;try{sessionStorage.setItem(storageKey,JSON.stringify({step,selected,speakingDone,writingDone}));}catch{}},[storageKey,hydrated,step,selected,speakingDone,writingDone]);
 function next(){setStep(s=>s+1);stepStarted.current=Date.now();setChecked(false);setError('');}
 async function advance(){if(step!==2&&step!==3){next();return;}setSaving(true);setError('');try{const kind=step===2?'listening':'reading';stepAttempts.current[kind]??=crypto.randomUUID();const minutes=Math.max(1,Math.min(30,Math.round((Date.now()-stepStarted.current)/60000)));await onPractice(kind,selected['step'+step]===question.answer?100:0,minutes,stepAttempts.current[kind]);practiceMinutes.current+=minutes;next();}catch(e){setError(e instanceof Error?e.message:'Your answer could not be saved. Please try again.');}finally{setSaving(false);}}
 async function complete(){setSaving(true);setError('');try{await onComplete(Math.max(1,Math.min(30,Math.round((Date.now()-started.current)/60000)-practiceMinutes.current)));try{sessionStorage.removeItem(storageKey);}catch{}setFinished(true);}catch(e){setError(e instanceof Error?e.message:'Your progress could not be saved. Please try again.');}finally{setSaving(false);}}
 const question=step===2?lesson.listening:lesson.reading;
 const quizCorrect=lesson.quiz.filter((q,i)=>selected['quiz'+i]===q.answer).length;
 const practiceCompleted=async (skill:string,score:number|null,minutes:number,attemptId?:string)=>{await onPractice(skill,score,minutes,attemptId);practiceMinutes.current+=minutes;if(skill==='speaking')setSpeakingDone(true);if(skill==='writing')setWritingDone(true);};
 if(finished)return <section className="panel completion"><span className="completion-icon"><CheckCircle2 size={48}/></span><p className="eyebrow">LITEN SEGER · A SMALL WIN</p><h1>Bra jobbat!</h1><p>You can now: {lesson.goal}</p><div className="result-strip"><span><b>{lesson.words.length}</b> words to revisit</span><span><b>{quizCorrect} / {lesson.quiz.length}</b> quiz answers correct</span><span><b>4</b> skills practised</span></div><p className="help-text">Your words are ready for spaced repetition in the Word bank.</p><button className="primary" onClick={onExit}>Back to my path <ArrowRight size={18}/></button></section>;
 return <div className="lesson-player"><button className="text-button back-link" onClick={onExit}><ArrowLeft size={16}/>Learning path</button><div className="lesson-heading"><span className="badge">{lesson.level} · {lesson.unit}</span><h1>{lesson.title}</h1><p>{lesson.goal}</p></div><div className="lesson-progress"><Progress aria-label="Lesson progress" value={(step/7)*100}/><span>Step {step+1} of 7 · {steps[step]}</span></div><div className="step-track">{steps.map((s,i)=><button onClick={()=>{if(i<=step){setStep(i);setChecked(false);}}} disabled={i>step} className={step===i?'selected':''} key={s}>{i<step?<Check size={14}/>:<span>{i+1}</span>}{s}</button>)}</div>
 <section className="panel lesson-panel">
 {step===0&&<><span className="section-symbol"><Layers/></span><h2>Six small building blocks</h2><p className="help-text">Listen, say each word out loud, then cover the English and try to remember it.</p><div className="vocab-grid">{lesson.words.map(w=><div key={w.id} className="vocab-tile"><div><strong lang="sv">{w.fi}</strong><AudioButton text={w.fi} className="icon-button" label={'Listen to '+w.fi}/></div><p>{w.en}</p><small lang="sv">{w.example}</small><span>{w.translation}</span></div>)}</div><div className="callout"><Volume2 size={22}/><div><b>Say it like this</b><p lang="sv">{lesson.pronunciation.text}</p><p>{lesson.pronunciation.tip}</p><AudioButton text={lesson.pronunciation.text} slow label="Listen slowly"/></div></div></>}
 {step===1&&<><span className="section-symbol"><BookOpen/></span><h2>{lesson.grammar.title}</h2><p className="long-copy">{lesson.grammar.explanation}</p><div className="example-list">{lesson.grammar.examples.map((e,i)=><div key={i}><b lang="sv">{e.fi}</b><span>{e.en}</span><AudioButton text={e.fi} className="icon-button" label="Listen to example"/></div>)}</div><div className="callout"><Sparkles size={20}/><p>Use the pattern in a sentence about your own life. You’ll remember it better when it means something to you.</p></div></>}
 {(step===2||step===3)&&<><span className="section-symbol">{step===2?<Headphones/>:<BookOpen/>}</span><h2>{step===2?'Listen for the meaning':'Read a little Swedish'}</h2>{step===2?<><p className="help-text">Listen once for the main idea. Listen again for the detail in the question.</p><div className="audio-exercise"><AudioButton text={question.text} label="Play Swedish audio"/><AudioButton text={question.text} slow label="Play slowly"/></div><button className="text-button" onClick={()=>setTranscript(!transcript)}>{transcript?'Hide':'Show'} transcript</button>{transcript&&<div className="reading-passage" lang="sv">{question.text}</div>}</>:<div className="reading-passage" lang="sv">{question.text}</div>}<h3 className="question-title">{question.question}</h3><div className="answer-list">{question.options.map((o,i)=><button key={o} disabled={checked} className={'answer-option '+(selected['step'+step]===i?'chosen ':'')+(checked&&i===question.answer?'correct':'')} onClick={()=>setSelected({...selected,['step'+step]:i})}><span>{String.fromCharCode(65+i)}</span>{o}{checked&&i===question.answer&&<Check size={18}/>}</button>)}</div>{checked&&<div className="feedback-box" role="status"><b>{selected['step'+step]===question.answer?'That’s right. Rätt!':'Good practice. Here’s the key detail:'}</b><p>{question.explanation}</p></div>}</>}
 {step===4&&<><h2>Your turn to speak</h2><p className="help-text">Speaking starts with trying. Record your voice or type what you said, then review it.</p><PracticeStudio initialSkill="speaking" level={lesson.level} lessonId={lesson.id} onComplete={practiceCompleted}/>{!speakingDone&&<p className="help-text">Save your speaking practice below to continue.</p>}</>}
 {step===5&&<><h2>Make the words your own</h2><p className="help-text">Write a response in Swedish. Use the model and checklist, or request AI feedback when connected.</p><PracticeStudio initialSkill="writing" level={lesson.level} lessonId={lesson.id} onComplete={practiceCompleted}/>{!writingDone&&<p className="help-text">Save your writing practice below to continue.</p>}</>}
 {step===6&&<><span className="section-symbol"><Sparkles/></span><h2>What stayed with you?</h2><p className="help-text">Try these without looking back. Mistakes tell you what to revisit.</p>{lesson.quiz.map((q,qi)=><div className="quiz-question" key={qi}><h3>{qi+1}. {q.question}</h3><div className="answer-list">{q.options.map((o,i)=><button key={o} disabled={checked} className={'answer-option '+(selected['quiz'+qi]===i?'chosen ':'')+(checked&&q.answer===i?'correct':'')} onClick={()=>setSelected({...selected,['quiz'+qi]:i})}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{checked&&<div className="feedback-box"><b>{selected['quiz'+qi]===q.answer?'Correct':'Keep practising'}</b><p>{q.explanation}</p></div>}</div>)}</>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 <div className="lesson-actions"><span>{step===0?'Listen. Repeat. Remember.':step===6?'Small steps add up.':'Take your time. You’re learning.'}</span>{(step===2||step===3)&&!checked?<button className="primary" disabled={selected['step'+step]===undefined} onClick={()=>setChecked(true)}>Check answer <Check size={16}/></button>:step===6?<button className="primary" disabled={saving||lesson.quiz.some((_,i)=>selected['quiz'+i]===undefined)} onClick={()=>checked?complete():setChecked(true)}>{saving?'Saving…':checked?'Complete lesson':'Check my answers'}<Check size={16}/></button>:<button className="primary" disabled={saving||(step===4&&!speakingDone)||(step===5&&!writingDone)} onClick={advance}>{saving?'Saving…':'Continue'} <ArrowRight size={16}/></button>}</div>
 </section></div>
}
